package com.raf.enums;

public enum NotificationType {
SHIPMENT_REQUEST,
PAYMENT_RECEIVED,
ORDER_CONFIRMED,
ORDER_SHIPPED,
ORDER_DELIVERED,
ENQUIRY_RECEIVED,
ENQUIRY_ACCEPTED,
ENQUIRY_REJECTED,
WAREHOUSE_ACCESS_SUBMITTED,
WAREHOUSE_ACCESS_APPROVED,
WAREHOUSE_ACCESS_REJECTED,
SYSTEM_ALERT,

USER_CREATED,
USER_UPDATED,
USER_DELETED,
WAREHOUSE_CREATED,
WAREHOUSE_UPDATED,
WAREHOUSE_DELETED,
INVENTORY_CREATED,
INVENTORY_UPDATED,
INVENTORY_DELETED,
CROP_TYPE_CREATED,
CROP_TYPE_UPDATED,
CROP_TYPE_DELETED
}

